apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.bitnami.com
spec:
  group: bitnami.com
  version: v1
  scope: Namespaced
  names:
    plural: apps
    singular: app
    kind: App
    shortNames:
    - app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kkcd-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kkcd-controller
    spec:
      containers:
      - name: kkcd-controller
        image: bitnami/kkcd-controller:latest
        env:
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
